#BIO DATA
Name=input("Enter the name")
College=input("Enter the college")
Age=int(input("Enter the Age"))
Height=float(input("Enter the heights"))
male=bool(input("ENTER THE MAle"))
print("My name is:",Name)
print("College:",College)
print("Age is ",Age)
print("Height is:",Height)
print("GENDER IS:",male)
